// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAjkHaVu0te3hSxafZQ_QrMNCE_fhWqEps",
    authDomain: "number-2-1650b.firebaseapp.com",
    projectId: "number-2-1650b",
    storageBucket: "number-2-1650b.appspot.com",
    messagingSenderId: "929684808307",
    appId: "1:929684808307:web:1ee3a9841b444bae12c006",
    measurementId: "G-LGH3CV6S6P",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4K0u6SXPR4EHtuuxsxVYo2ycfYBUyQW4',
    appId: '1:929684808307:android:20d9a41837b2ff2d12c006',
    messagingSenderId: '929684808307',
    projectId: 'number-2-1650b',
    storageBucket: "number-2-1650b.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyuirkSHUPowForJFmXgQwyY5erDa0Syk',
    appId: '1:929684808307:ios:5e0840a46ab8b15512c006',
    messagingSenderId: '929684808307',
    projectId: 'number-2-1650b',
    storageBucket: 'number-2-1650b.appspot.com',
    iosClientId:
        '929684808307-6sldlr38ma73q98ks141n79u81re2m8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutternumber2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyuirkSHUPowForJFmXgQwyY5erDa0Syk',
    appId: '1:929684808307:ios:5e0840a46ab8b15512c006',
    messagingSenderId: '929684808307',
    projectId: 'number-2-1650b',
    storageBucket: 'number-2-1650b.appspot.com',
    iosClientId:
        '929684808307-6sldlr38ma73q98ks141n79u81re2m8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutternumber2',
  );
}
